// ─────────────────────────────────────────────────────────────────────────────
// FamilyEventGenerator
// Ported from FamilyEventGenerator.swift (235 lines)
// Generates FamilyCalendarEvent objects for birthdays and Śrāddham.
// ─────────────────────────────────────────────────────────────────────────────

import { analyze, consecutiveMonthInstances } from '../engine/NakshatraAnalyzer'
import { shraddhamDates } from './ShraddhamFinder'
import type { PanchangamDay } from '../models/PanchangamDay'
import type { PersonProfile, FamilyCalendarEvent } from '../models/FamilyTypes'
import { NAKSHATRAS, MALAYALAM_MONTHS, TITHIS } from '../models/MalayalamCalendar'

// ---------------------------------------------------------------------------
// Birthday events
// ---------------------------------------------------------------------------
export function birthdayEvents(profile: PersonProfile, days: PanchangamDay[]): FamilyCalendarEvent[] {
  const birth = profile.birthDetails
  if (!birth?.birthNakshatra !== false && birth?.birthNakshatra === undefined) return []
  if (birth?.birthNakshatra === undefined || birth?.birthMalayalamMonth === undefined) return []

  const nakshatra = birth.birthNakshatra
  const month     = birth.birthMalayalamMonth
  const prefs     = profile.reminderPreferences

  const instances = consecutiveMonthInstances(month, days)
  const events: FamilyCalendarEvent[] = []

  for (const instanceDays of instances) {
    const { recommendedDays } = analyze(nakshatra, month, instanceDays, prefs.birthdayNakshatraPolicy)
    if (recommendedDays.length === 0) continue
    const day = recommendedDays[0]  // take only first of the recommendation (no duplicates)
    const startDate = eventDate(day, prefs.birthdayReminderHour, prefs.birthdayReminderMinute)
    events.push({
      title: `${displayName(profile)} Star Birthday`,
      startDate,
      endDate: new Date(startDate.getTime() + 30 * 60_000),
      notes: birthdayNotes(profile, day),
      personId: profile.id,
    })
  }
  return events
}

// ---------------------------------------------------------------------------
// Śrāddham events
// ---------------------------------------------------------------------------
export function shraddhamEvents(profile: PersonProfile, days: PanchangamDay[]): FamilyCalendarEvent[] {
  if (!profile.deathDetails) return []
  const prefs = profile.reminderPreferences
  return shraddhamDates(profile, days, prefs.shraddhamMode).map(sd => {
    const startDate = new Date(sd.gregorianDate)
    startDate.setUTCHours(prefs.shraddhamReminderHour, prefs.shraddhamReminderMinute, 0, 0)
    return {
      title: `${displayName(profile)} Śrāddham`,
      startDate,
      endDate: new Date(startDate.getTime() + 30 * 60_000),
      notes: shraddhamNotes(profile, sd),
      personId: profile.id,
    }
  })
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function displayName(p: PersonProfile): string {
  return p.nickname.trim() !== '' ? p.nickname : p.fullName
}

function eventDate(day: PanchangamDay, hour: number, minute: number): Date {
  const d = new Date(day.date)
  d.setUTCHours(hour, minute, 0, 0)
  return d
}

function birthdayNotes(profile: PersonProfile, day: PanchangamDay): string {
  const lines = [
    `Person: ${displayName(profile)}`,
    `Event: Star Birthday`,
    `Nakshatra: ${NAKSHATRAS[day.mainNakshatra].english}`,
    `Malayalam Date: ${MALAYALAM_MONTHS[day.malayalamMonth].english} ${day.malayalamDay}, ${day.kollavarshamYear}`,
    `Generated by Malayalam Panchangam Web App`,
  ]
  return lines.join('\n')
}

import type { ShraddhamDate } from '../models/FamilyTypes'

function shraddhamNotes(profile: PersonProfile, sd: ShraddhamDate): string {
  const tithi = TITHIS[sd.tithi]
  return [
    `Person: ${displayName(profile)}`,
    `Event: Śrāddham`,
    `Tithi: ${sd.paksha === 'shukla' ? 'S' : 'K'} ${tithi.english}`,
    `Date: ${sd.malayalamDateLabel}`,
    `Rule: ${sd.selectionRuleDescription}`,
    `Disclaimer: Verify with family tradition or a trusted astrologer/priest.`,
  ].join('\n')
}
