import Foundation

struct MalayalamReminderEventGenerator: ReminderEventGenerating {
    func events(for reminder: MalayalamReminder, in days: [PanchangamDay]) async -> [CalendarEvent] {
        matchingDays(for: reminder, in: days).compactMap { day in
            guard let start = eventDate(for: day, reminder: reminder) else { return nil }
            return CalendarEvent(
                title: reminder.name,
                startDate: start,
                endDate: start.addingTimeInterval(30 * 60),
                notes: eventNotes(for: reminder, day: day),
                sourceReminderID: reminder.id
            )
        }
    }

    func alerts(for reminder: MalayalamReminder, in days: [PanchangamDay]) async -> [PanchangamAlert] {
        matchingDays(for: reminder, in: days).compactMap { day in
            guard let eventDate = eventDate(for: day, reminder: reminder) else { return nil }
            let fireDate = eventDate.addingTimeInterval(-TimeInterval(reminder.advanceMinutes * 60))
            return PanchangamAlert(
                title: reminder.name,
                body: alertBody(for: reminder, day: day),
                fireDate: fireDate
            )
        }
    }

    private func matchingDays(for reminder: MalayalamReminder, in days: [PanchangamDay]) -> [PanchangamDay] {
        days.filter { day in
            let monthMatches = reminder.malayalamMonth == nil || reminder.malayalamMonth == day.malayalamMonth
            let dayMatches = reminder.malayalamDay == nil || reminder.malayalamDay == day.malayalamDay
            let starMatches = reminder.nakshatra == nil || reminder.nakshatra == day.mainNakshatra
            return monthMatches && dayMatches && starMatches
        }
    }

    private func eventDate(for day: PanchangamDay, reminder: MalayalamReminder) -> Date? {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = day.location.timeZone
        let hour = reminder.reminderTime.hour ?? 7
        let minute = reminder.reminderTime.minute ?? 0
        return calendar.date(bySettingHour: hour, minute: minute, second: 0, of: day.date)
    }

    private func eventNotes(for reminder: MalayalamReminder, day: PanchangamDay) -> String {
        [
            "Generated by Malayalam Panchangam Calendar.",
            "Malayalam date: \(day.malayalamMonth.englishName) \(day.malayalamDay), \(day.kollavarshamYear).",
            "Nakshatra: \(day.mainNakshatra.englishName).",
            "Reminder type: \(reminder.kind.rawValue).",
            "Generated as an individual event, not an EventKit recurring rule."
        ].joined(separator: "\n")
    }

    private func alertBody(for reminder: MalayalamReminder, day: PanchangamDay) -> String {
        "\(day.malayalamMonth.englishName) \(day.malayalamDay) • \(day.mainNakshatra.englishName)"
    }
}
